export default [
  '"In the name of Allah, the Entirely Merciful, the Especially Merciful." — Quran 1:1',
  '"So verily, with the hardship, there is relief." — Quran 94:5',
  '"Therefore remember Me (by praying, glorifying, etc.). I will remember you, and be grateful to Me and never be ungrateful to Me." — Quran 2:152',
  '"Then which of the Blessings of your Lord will you both (jinn and men) deny?" — Quran 55:13',
  '"Say (O Muhammad (Peace be upon him)): "He is Allah, One (i.e. Allah has no partners or no one is equal to Him)." — Quran 112:1',
  '"Allah-us-Samad (The Self-Sufficient Master, Whom all creatures need, He neither eats nor drinks)." — Quran 112:2',
  '"O you who believe! Remember Allah with much remembrance." — Quran 33:41',
  '"Allah burdens not a person beyond his scope." — Quran 2:286',
  '"And whosoever puts his trust in Allah, then He will suffice him." — Quran 65:3',
  '"Those who believed (in the Oneness of Allah - Islamic Monotheism), and whose hearts find rest in the remembrance of Allah, verily, in the remembrance of Allah do hearts find rest." — Quran 13:28',
  '"And your Lord said: "Invoke Me, I will respond to your (invocation)." — Quran 40:60',
  '"O you who believe! Seek help in patience and As-Salat (the prayer). Truly! Allah is with As-Sabirin (the patient ones)." — Quran 2:153',
  '"And say: "My Lord! Increase me in knowledge." — Quran 20:114',
  '"And We are nearer to him than his jugular vein (by Our Knowledge)." — Quran 50:16',
  '"He it is Who created the heavens and the earth in six Days and then Istawa (rose over) the Throne (in a manner that suits His Majesty). He knows what goes into the earth and what comes forth from it, and what descends from the heaven and what ascends thereto. And He is with you (by His Knowledge) wheresoever you may be. And Allah is the All-Seer of what you do." — Quran 57:4',
  '"And those who strive in Our (Allah\'s) Cause, We will certainly guide them to Our Paths (i.e. Allah\'s Religion - Islamic Monotheism). And verily, Allah is with the Muhsinun (good doers)." — Quran 29:69',
  '"Say: "O \'Ibadi (My slaves) who have transgressed against themselves! Despair not of the Mercy of Allah, verily Allah forgives all sins. Truly, He is Oft-Forgiving, Most Merciful." — Quran 39:53',
  '"So do not become weak (against your enemy), nor be sad, and you will be superior (in victory) if you are indeed (true) believers." — Quran 3:139',
  '"Truly, those who believe and do righteous good deeds, and humble themselves before their Lord, they will be dwellers of Paradise to dwell therein forever." — Quran 11:23',
  '"And I (Allah) created not the jinns and humans except they should worship Me (Alone)." — Quran 51:56',
  '"O you who believe! Fear Allah (by keeping your duty to Him and avoid all kinds of sins and evil deeds which He has forbidden), and die not except in a state of Islam (as Muslims)." — Quran 3:102',
  '"O you who believe! Fear Allah and keep your duty to Him. And let every person look to what he has sent forth for the morrow, and fear Allah. Verily, Allah is All-Aware of what you do." — Quran 59:18',
  '"Everyone is going to taste death, and We shall make a trial of you with evil and with good, and to Us you will be returned." — Quran 21:35',
  '"Did you think that We had created you in play (without any purpose), and that you would not be brought back to Us?" — Quran 23:115',
  '"He Who created death and life that He may test you which of you is best in deed. And He is the All-Mighty, the Oft-Forgiving." — Quran 67:2',
  '"Wealth and children are the adornment of the life of this world. But the good righteous deeds (five compulsory daily prayers, etc.), that last, are better with your Lord for rewards and better in respect of hope." — Quran 18:46',
  '"Indeed, whosoever purifies himself shall achieve success. And remembers the Name of his Lord, and prays." — Quran 87:14-15',
  '"O mankind! Verily, the Promise of Allah is true. So let not this present life deceive you." — Quran 35:5',
  '"Whoever works righteousness, whether male or female, while he (or she) is a true believer (of Islamic Monotheism) verily, to him We will give a good life (in this world with respect, contentment and lawful provision), and We shall pay them certainly a reward in the hereafter that will be greater than (the reward of) their worldly deeds." — Quran 16:97',
  '"And when My slaves ask you (O Muhammad (Peace be upon him)) concerning Me, then (answer them), I am indeed near (to them by My Knowledge). I respond to the invocations of the supplicant when he calls Me (without any mediator or intercessor)." — Quran 2:186',
  '"O you who believe! If you obey and fear Allah, He will grant you Furqan (a criterion to judge between right and wrong), and will expiate from you your sins, and will forgive you. And Allah is the Owner of the Great Bounty." — Quran 8:29',
  '"And remember your Lord by your tongue and within yourself, humbly and with fear without loudness in words, in the mornings and in the afternoons, and be not of those who are neglectful." — Quran 7:205',
  '"Whosoever does good equal to the weight of an atom (or a small ant), shall see it. And whosoever does evil equal to the weight of an atom (or a small ant), shall see it." — Quran 99:7-8',
  '"By Al-\'Asr (the time). Verily! Man is in loss, except those who believe (in Islamic Monotheism) and do righteous good deeds, and recommend one another to the truth (i.e. order one another to perform all kinds of good deeds which Allah has ordained), and recommend one another to patience (for the sufferings, harms, and injuries which one may encounter)." — Quran 103:1-3',
  '"And (remember) when your Lord proclaimed: "If you give thanks (by accepting Faith, worshipping none but Allah), I will give you more (of My Blessings), but if you are thankless (i.e. disbelievers), verily! My Punishment is indeed severe." — Quran 14:7',
  '"O mankind! Be afraid of your Lord (by keeping your duty to Him and avoiding all evil), and fear a Day when the father cannot avail his son in aught, nor can the son avail his father in aught." — Quran 31:33',
  '"The mutual rivalry (for piling up of worldly things) diverts you, until you visit the graves (i.e. till you die)." — Quran 102:1-2',
  '"Verily, over you (are appointed angels in charge of mankind) to watch you, Kiraman (honourable) Katibin (writing down your deeds). They know all that you do." — Quran 82:10-12',
  '"And follow not (O man i.e., say not, or do not, or witness not, etc.) that of which you have no knowledge (in speech, action, or belief). Verily! The hearing, and the sight, and the heart, of each of those you will be questioned (by Allah)." — Quran 17:36',
  '"Know that the life of this world is only play and amusement, pomp and mutual boasting among yourselves, and rivalry in respect of wealth and children." — Quran 57:20',
  '"Indeed, We have created man from drops of mixed semen (sexual discharge of man and woman), in order to try him, so We made him hearer, seer." — Quran 76:2',
  '"O you who believe! Endure and be more patient (than your enemy), and guard your territory by stationing army units permanently at the places from where the enemy can attack you, and fear Allah, so that you may be successful." — Quran 3:200',
  '"So keep your duty to Allah as much as you can, and listen and obey, and spend in Charity (that is better for yourselves). And whosoever is saved from his own covetousness, then they are the successful ones." — Quran 64:16',
  '"O mankind! We have created you from a male and a female, and made you into nations and tribes, that you may know one another. Verily, the most honourable of you with Allah is that (believer) who has At-Taqwa (i.e. one of the Muttaqun - pious and righteous persons). Verily, Allah is All-Knowing, All-Aware." — Quran 49:13',
  '"And remember the Name of your Lord every morning and evening. And during night, prostrate yourself to Him, and glorify Him a long night through." — Quran 76:25-26',
  '"And seek help in patience and As-Salat (the prayer) and truly it is extremely heavy and hard except for Al-Khashi\'un [i.e. the true believers in Allah - those who obey Allah with full submission, fearing much from His Punishment, and believe in His Promise (Paradise) and His Warnings (Hell)]." — Quran 2:45',
  '"Fear Allah, and know that Allah is the Best of those who keep watch." — Quran 4:1',
  '"Every person is a pledge for what he has earned." — Quran 74:38',
  '"O my son! If it be (anything) equal to the weight of a grain of mustard seed, and though it be in a rock, or in the heavens or in the earth, Allah will bring it forth. Verily, Allah is Subtle (in bringing out that grain), Well-Aware (of its place)." — Quran 31:16',
  '"O you who believe! Keep your duty to Allah and fear Him, and speak (always) the truth. He will direct you to do righteous good deeds and will forgive you your sins. And whosoever obeys Allah and His Messenger (Peace be upon him) he has indeed achieved a great achievement (i.e. he will be saved from the Hell-fire and made to enter Paradise)." — Quran 33:70-71'
]
