export default [
  '"In the Name of Allah, the Most Gracious, the Most Merciful." — Quran 1:1',
  '"Verily, along with every hardship is relief." — Quran 94:5',
  '"Therefore remember Me, I will remember you, and be grateful to Me and never be ungrateful to Me." — Quran 2:152',
  '"Then which of the Blessings of your Lord will you both deny?" — Quran 55:13',
  '"Say: He is Allah, the One." — Quran 112:1',
  '"Allah, the Self-Sufficient Master, Whom all creatures need." — Quran 112:2',
  '"O you who believe! Remember Allah with much remembrance." — Quran 33:41',
  '"Allah burdens not a person beyond his scope." — Quran 2:286',
  '"And whosoever puts his trust in Allah, then He will suffice him." — Quran 65:3',
  '"Verily, in the remembrance of Allah do hearts find rest." — Quran 13:28',
  '"And your Lord said: Invoke Me, I will respond to your invocation." — Quran 40:60',
  '"O you who believe! Seek help in patience and the prayer. Truly, Allah is with the patient." — Quran 2:153',
  '"O my Lord! Open for me my chest." — Quran 20:25',
  '"And We are nearer to him than his jugular vein." — Quran 50:16',
  '"And He is with you wheresoever you may be." — Quran 57:4',
  '"As for those who strive hard in Us, We will surely guide them to Our Paths." — Quran 29:69',
  '"Despair not of the Mercy of Allah." — Quran 39:53',
  '"So do not become weak, nor be sad, and you will be superior if you are indeed believers." — Quran 3:139',
  '"Only those who are patient shall receive their reward in full, without reckoning." — Quran 39:10'
]
