import defaultCustomMessages from './defaultCustomMessages.js'
import defaultQuranAyats from './defaultQuranAyats.js'
import { insideFlatpak, insideWindowsStore, insideSnap, insideWindowsPortable } from './utils.js'

export default {
  microbreakDuration: 20000,
  microbreakInterval: 600000,
  microbreakNotification: true,
  microbreakNotificationInterval: 10000,
  microbreak: true,
  microbreakStrictMode: false,
  morningHour: 6,
  mainColor: '#26A69A',
  miniBreakColor: '#26A69A',
  transparentMode: false,
  blurredBackground: false,
  opacity: 0.9,
  fullscreen: true,
  naturalBreaks: true,
  naturalBreaksInactivityResetTime: 300000,
  allScreens: true,
  language: 'en',
  notifyNewVersion: true,
  isFirstRun: true,
  posLatitude: 0.0,
  posLongitude: 0.0,
  useMonochromeTrayIcon: false,
  useMonochromeInvertedTrayIcon: false,
  monitorDnd: true,
  themeSource: 'system',
  endBreakShortcut: 'CmdOrCtrl+X',
  breakWindowWidth: 1.0,
  breakWindowHeight: 1.0,
  checkNewVersion: true,
  showBreaksAsRegularWindows: false,
  appExclusions: [],
  appExclusionsCheckInterval: 1000,
  pauseForSuspendOrLock: true,
  pauseBreaksToggleShortcut: '',
  pauseBreaksFor30MinutesShortcut: '',
  pauseBreaksFor1HourShortcut: '',
  pauseBreaksFor2HoursShortcut: '',
  pauseBreaksFor5HoursShortcut: '',
  pauseBreaksUntilMorningShortcut: '',
  screen: 'primary',
  trayIconStyle: 'default',
  currentTimeInBreaks: false,
  showTrayIcon: true,
  skipToNextScheduledBreakShortcut: '',
  skipToNextMiniBreakShortcut: '',
  resetBreaksShortcut: '',
  showTrayMenuInStrictMode: false,
  customPreferencesMessage: '',
  disableAppUpdateFeatures: insideFlatpak() || insideWindowsStore() || insideSnap() || insideWindowsPortable(),
  hidePreferencesFileLocation: false,
  hideStrictModePreferences: false,
  miniBreakManualFinish: false,
  openAtLogin: true,
  _migratedOpenAtLogin: false,
  customBreakMessage: '',
  customMessageList: defaultCustomMessages,
  customMessagesEnabled: true,
  quranAyatEnabled: true,
  quranAyats: defaultQuranAyats,
  islamicReminders: [
    'You have been working — pause and remember your intention. Is it for Allah\'s sake?',
    'You became absorbed in work. Take a moment to remember Allah.',
    'Don\'t let productivity make you forget the One who gave you the ability to work.',
    'Pause. Say Bismillah. Renew your intention.',
    'Your work is ibadah only if your intention is right. Check it now.',
    'You have been focused on the dunya. Take a moment for your akhirah.',
    'Allah is watching you right now. Are you mindful of Him?',
    'Step back. Make dhikr. Then continue with barakah.',
    'A moment of remembrance of Allah is better than hours of heedless work.',
    'Refresh your niyyah. Are you working to please Allah or just to please yourself?',
    'You will stand before Allah — He will ask how you spent this time. Make it count.',
    'Your eyes, your time, and your energy are trusts from Allah. Guard them even while working.',
    'SubhanAllah, Alhamdulillah, Allahu Akbar — say it now before you continue.',
    'Have you prayed on time today? Don\'t let work delay your salah.',
    'The best workers are those who remember Allah in the midst of their labor.'
  ],
  islamicRemindersEnabled: true,
  ayahIndex: 0,
  reminderIndex: 0,
  lastMessageType: 0,
  themeIndex: 0,
  themeColors: ['#26A69A', '#2196F3', '#3F51B5', '#9C27B0', '#E91E63', '#F44336', '#FF9800', '#FFC107', '#4CAF50', '#00BCD4']
}
