import defaultCustomMessages from './defaultCustomMessages.js'
import defaultQuranAyats from './defaultQuranAyats.js'
import { insideFlatpak, insideWindowsStore, insideSnap, insideWindowsPortable } from './utils.js'

export default {
  microbreakDuration: 20000,
  microbreakInterval: 600000,
  microbreakNotification: true,
  microbreakNotificationInterval: 10000,
  microbreak: true,
  microbreakStrictMode: false,
  morningHour: 6,
  microbreakPostpone: true,
  microbreakPostponeTime: 120000,
  microbreakPostponesLimit: 1,
  microbreakPostponableDurationPercent: 30,
  mainColor: '#26A69A',
  miniBreakColor: '#26A69A',
  transparentMode: false,
  blurredBackground: false,
  opacity: 0.9,
  miniBreakAudio: 'crystal-glass',
  volume: 1,
  fullscreen: true,
  naturalBreaks: true,
  naturalBreaksInactivityResetTime: 300000,
  allScreens: true,
  language: 'en',
  notifyNewVersion: true,
  isFirstRun: true,
  posLatitude: 0.0,
  posLongitude: 0.0,
  useMonochromeTrayIcon: false,
  useMonochromeInvertedTrayIcon: false,
  silentNotifications: false,
  monitorDnd: true,
  miniBreakStartSound: 'silence',
  themeSource: 'system',
  endBreakShortcut: 'CmdOrCtrl+X',
  breakWindowWidth: 1.0,
  breakWindowHeight: 1.0,
  checkNewVersion: true,
  showBreaksAsRegularWindows: false,
  appExclusions: [],
  appExclusionsCheckInterval: 1000,
  pauseForSuspendOrLock: true,
  pauseBreaksToggleShortcut: '',
  pauseBreaksFor30MinutesShortcut: '',
  pauseBreaksFor1HourShortcut: '',
  pauseBreaksFor2HoursShortcut: '',
  pauseBreaksFor5HoursShortcut: '',
  pauseBreaksUntilMorningShortcut: '',
  screen: 'primary',
  trayIconStyle: 'default',
  currentTimeInBreaks: false,
  showTrayIcon: true,
  skipToNextScheduledBreakShortcut: '',
  skipToNextMiniBreakShortcut: '',
  resetBreaksShortcut: '',
  showTrayMenuInStrictMode: false,
  customPreferencesMessage: '',
  disableAppUpdateFeatures: insideFlatpak() || insideWindowsStore() || insideSnap() || insideWindowsPortable(),
  hidePreferencesFileLocation: false,
  hideStrictModePreferences: false,
  miniBreakManualFinish: false,
  openAtLogin: true,
  _migratedOpenAtLogin: false,
  customBreakMessage: '',
  customMessageList: defaultCustomMessages,
  customMessagesEnabled: true,
  quranAyatEnabled: true,
  quranAyats: defaultQuranAyats
}
